version: '3.3'
services:
  unpub:
    build: ./
    container_name: unpub
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - mongo
  mongo: 
    image: mongo:4.2.19
    container_name: unpub_mongo 
    restart: always
    volumes: 
      - ~/.unpub_mongo:/data/db